window.corpus = [
    "quelle belle journee",
    "le ciel est bleu",
    "la terre est plate",
    "si je rempli mon verre il sera rempli",
    "je crois que le belvedere est de travers",
    "le rugby est un sport d equipe",
    "attention a la marche en descendant du train",
    "il est indubitablement grand",
    "justifiez votre acte",
    "trouver le chemin vers le village",
    "dormez paisiblement en cette belle nuit",
    "obtemperez ou mourrez",
    "la glace a la vanille est le meilleur choix",
    "publiez cet article sur le journal",
    "le destin de cet insecte est tout trace",
    "voulez vous dormir sur le canape",
    "melanger le sucre et la farine",
    "quelle delicieuse journee",
    "la poule est un animal diurne",
    "sans desespoir il n'y a pas d espoir",
    "les humains sont nes dans le feu",
    "produire du lait de maniere massive",
    "l enfer c est les autres",
    "j aime les compotes de pommes",
    "votre point de vue est legitime",
    "detruire et creer sont des principes lies",
    "ce n est qu une question de temps",
    "vous avez une superbe memoire",
    "mangerez vous du choux",
    "cinq cents ans apres il garde son eclat",
    "je suis subjugue par cette paire de chaussures",
    "klaxonner dans un embouteillage est inutile",
    "former les bataillons",
    "exercer un grand ascendant sur quelqu un",
    "qualifie un courant d air qui se dirige vers le haut",
    "un astre au dessus de l horizon",
    "ces trublions succedent au cachet therapeutique",
    "la racaille ne nuit plus tres bien au substitut",
    "nous nous inspirerons de trois parodies froides",
    "le garde du corps se lamentait sur les pigistes",
    "une survivante souhaite partir dans le calvados",
    "jacques mesrine feignait d inhaler les voyeuses",
    "la fee clochette s interrogeait sur les phallus",
    "l hypocrite brule des celebrites catatoniques",
    "tu acceptes facilement de bronzer en batifolant",
    "le compositeur propose nos cercles a des poetes",
    "nous transportions les phrases l annee derniere",
    "sous les arbres cet agent en immobilier rigole",
    "elles hesiteront a clarifier certains demineurs",
    "des fournisseurs offrent une armure a l arbitre",
    "segolene royal se limite a jardiner clairement ",
    "il repose particulierement mal sur tes genoux",
    "le bouc emissaire vouvoiera une griffe de tigre",
    "rosa luxembourg se consacrera a treize manies",
    "un garcon surexcite erre huit fois par semaine ",
    "les flibustiers se degonflent a portee de main ",
    "les entraineuses senior deposaient les poussins",
    "ces politiciennes proviennent des armes a feu",
    "la speculatrice senior glisse sur un itineraire",
    "des photographes devront ne pas encore eternuer",
    "guy lux se rabat sur la vegetarienne pessimiste",
    "les arabes se passaient des socialistes sveltes",
    "la directrice persiste a compromettre ce projet",
    "le cretin adorera fantasmer n importe comment",
    "une marseillaise bipolaire nie mimer un torse",
    "le maitre a penser de catherine jacob riposte",
    "la doublure de jack palance eleve une direction",
    "n importe qui se trouve en floride pour rigoler",
    "une marquise s associe aux vacances en saignant",
    "des copines affirment gonfler irrationnellement",
    "elles nient abandonner une myriade d opuscules ",
    "a mon signal une entite acceptera de barboter ",
    "gerard jugnot revient dans une autre dimension ",
    "nous nous permettons de benir des francs macons",
    "nous affirmons mediter sur un tendon circulaire",
    "elles promettent de tendres mouches a l artiste",
    "un larbin accoutume au luxe consulte une mangue",
    "une geneuse maladroite ne priait presque jamais",
    "condoleezza rice plonge calmement au restaurant",
    "des grevistes se mesurent a ces grains de sable",
    "la senegalaise s exerce a se pointer en irlande",
    "toutes les connasses selectionnent des crachats",
    "albert einstein ne proscrira pas des grossistes",
    "l herbivore rebondira sur les cadres superieurs",
    "ces cochers se mesureront a un groupe de manies",
    "ils associeront une allumette et onze registres",
    "cinq communistes enrages comptent un programme ",
    "un philologue se consacre a ton copain plombier",
    "jesus confisquera ces reacteurs a ray charles",
    "jose bove approche de soixante dix ratatouilles",
    "des ecrivains bourres d antibiotiques pavoisent",
    "un medecin empiete sur quelques grains de sable",
    "la folle commande une reponse a des farandoles ",
    "le proxenete aime succeder au velocipede a midi",
    "elles se dispensaient de s opposer a ces chiens",
    "une femme sur quatre murmure sans ressusciter",
    "plusieurs gerontologues parvenaient a chipoter ",
    "des galopins se plantaient en face du cimetiere",
    "les refugies corpulents tapent sur des clientes",
    "vous comparez les gouverneurs et les echanges",
    "le glandeur approche de mes grenades avec brio ",
    "des paysans parlementeront quand je serai grand",
    "des assesseurs nuisaient a un lance roquettes",
    "le participant refuse quelques masses rouillees",
    "peu de fiscalistes approcheront d une saloperie",
    "rama yade reviendra heriter du noyau inadapte",
    "cette femme completement ivre arrive a speculer",
    "les alcooliques produisent des tireurs d elite ",
    "trois bricoleurs du dimanche habitent a atlanta",
    "des explorateurs bavards s installent au soleil",
    "des aide soignants s attaquent a des charlatans",
    "elle ne se gauffre pas sur la place du marche",
    "ta mere rode en retenant des dizaines d alarmes",
    "certains portugais egaient tes vaines promesses",
    "les arabes hirsutes manipulent quatre ricochets",
    "des emissaires se mettent a choyer fanny ardant",
    "des dizaines de rescapees revelaient l helice",
    "les actionnaires crucifient le trognon de pomme",
    "les hypnotiseurs uniront l imposture et un role",
    "ces marchands d esclaves tirent francois fillon",
    "les cobayes aiment echapper aux investigatrices",
    "un journaliste sur cent se mettait a perseverer",
    "nous parlons d un ecrivain six fois par semaine",
    "elle approche d une vertu en convoyant ce debit",
    "quelques monstres courent sans la moindre honte",
    "les donatrices se debrouilleront au meme moment",
    "nous peinerons a nous exprimer en nous relevant",
    "nous alignions douze luges avec dix neuf cactus",
    "je dis me rapprocher en douce de potentiometres",
    "les manifestants vomissent sur des psychopathes",
    "le speculateur sejourne aux alentours de mexico",
    "un compere s enorgueillit de plusieurs octaves ",
    "ces chinois decortiquent ces sportifs enrhumes ",
    "des feaux aplatissent ces oubliettes mentales",
    "la presentatrice de la meteo diminue des pepins",
    "les bouddhistes stationnent dans un photomaton ",
    "des limiers souhaiteront refuter l andouillette",
    "l aide soignant arrogant devalisait des hangars",
    "je separe les faces circulaires et une fonction",
    "ces juges de touche telephonent a la magicienne",
    "les conscrites mercenaires aspireront a papoter",
    "le pigiste accouche de visiteurs sous calmants ",
    "la lorelei jette un lievre a une mine reguliere",
    "tu croqueras des tas de frondes a deux vitesses",
    "un imam progressiste ose influer sur la science",
    "un couturier au groin gluant se faufile en inde",
    "les pilotes de ligne heriteront de mes ouragans",
    "des toxicomanes s inspiraient d une compilation",
    "je m oppose aux bidets en redoutant des regimes",
    "je semble entrer a onze kilometres vers le nord",
    "le beau frere de don quichotte affirmera partir",
    "la victime s equipe de nos additions ignifugees",
    "le prestidigitateur choisit l incendie de foret",
    "des voyageurs nient insister sur ce laboratoire",
    "le depute empietera sur celui qui nous manipule",
    "une virtuose cruelle avoue penser a un tracteur",
    "un ami de baruch spinoza replacera des sommets ",
    "soixante plaignants trimbalaient des esquives",
    "une organisatrice se consacre a une enorme epee",
    "l arbitre pourchassera les cancres analphabetes",
    "les ferrailleurs vendent les oliviers motorises",
    "cecile de france aime se referer aux impulsions",
    "des deglingues separent la verite et des bijoux",
    "nous ne nous enorgueillissons pas des allemands",
    "en irlande une courtisane geint sans cotiser",
    "l halterophile habite en orbite geostationnaire",
    "nous nous retrouvons a bord du wagon restaurant",
    "le delinquant cabossera une excellente surprise",
    "les allumeurs de reverberes mimeront des lianes",
    "des gardiens de but deplacent la charge bizarre",
    "je songe aux enseignants possedes par le diable",
    "des sauvages daignent correspondre a un fossile",
    "nous nous calquions sur les teintes de carnaval",
    "le seul ami du roi arthur s inspirait du centre",
    "des plombiers s opposent a ces nanas a l infini",
    "sigmund freud et ses avocats mordent une souris",
    "un eleve decorait l epuisette avec ces patins",
    "peu de pietons adorent recuperer une gargouille",
    "les prefets s opposent aux tartes a la rhubarbe",
    "dracula teste des reticules sans foncer en iran",
    "les laveurs de carreaux vouvoieront l oligarque",
    "la passante ne detestait pas deplorer les caids",
    "deux membres du parti s inscrivent pour sombrer",
    "certains gnomes hirsutes depassent les sifflets",
    "j escamotais un gâteau au chocolat en soupirant",
    "alf balance des sacoches agees de treize mois",
    "joe dalton presentait le fourneau a un nanceien",
    "des colonels aiment penser a un inconnu en inde",
    "le mari de dorothee s amuse a plonger au soudan",
    "le margoulin promettra d apporter ces poubelles",
    "presque toutes les filles filaient a disneyland",
    "ils reveront d errer pour se trouver sous terre",
    "le roi de la piste ne se gave pas de conditions",
    "la plupart des sorcieres trinquent a nos listes",
    "un technocrate table sur des milliers de coupes",
    "des allemandes choment en balayant leur sardine",
    "tu nettoyais des opportunites avec deux arteres",
    "vous filez sur la lune en distancant des ruses ",
    "je honnirai furieusement un funiculaire local",
    "aux alentours de mexico vous ne vous noyez pas",
    "un danseur fetichiste du nombre huit recule",
    "une espionne distance simone veil sans etouffer",
    "le chasseur defend une lame avec une anacoluthe",
    "romy schneider pulverisait tout un tas de trucs",
    "dans un avion des croque morts font le bouquin",
    "l association souffrira de ronronner en irlande",
    "j admets ramener l assaillant aux celibataires ",
    "jean paul sartre guy lux et toi vous morfondez",
    "ils se referent a des tremplins tous les matins",
    "l adjoint au maire declare rever de l arabesque",
    "a dubai des artistes contribueront a un regard",
    "le deglingue engage secouera une brosse a dents",
    "un ami de mireille mathieu humera sigmund freud",
    "un ami de michel boujenah se refere a des roles",
    "vous enveloppez les boissons avec son bilboquet",
    "je repose sur des pilotes de ligne analphabetes",
    "vous revenez songer au chat d arlette laguiller",
    "vous n osez pas conduire des critiques de films",
    "des patrons se munissent d un nain ventripotent",
    "au qatar la princesse leia reunit des bananes ",
    "elle aplatit les detonations avec les regimes",
    "onze goinfres diserts cuisent des compilations ",
    "un chocolatier amateur ronronne a toute vitesse",
    "nous allions grogner sur les berges de la loire",
    "francois hadji lazaro analysait des materiaux",
    "une brute epaisse se rapproche d un poissonnier",
    "le premier amour de dan simmons nie se soulever",
    "des greffiers declarent tousser sous les ponts "
];